### ISSUE TITLE
Idea: `--resolve-oldest` option to resolve to oldest available dependency

### ISSUE THREAD

**Issue by Schwad** [flavorjones/bundler-as_of#2]
I've been using this amazing plugin pretty heavily this weekend!

I often deal with code that pushes the limits of what's available on rubygems. So I frequently get dependencies resolving to 2022/latest when actually trying to pick up quite an old dependency. 

I don't think that core functionality of this gem should change. The warning and defaulting to a normal bundle install is fine.

But perhaps there is a usecase to add an option/flag to ask the versionfinder to resolve to the oldest available dependency if it can't find one?

I'm sorry this is via an issue and not a PR. I'm just documenting this here and if you think it's feasible am happy to pick this up after March. :)

**Comment by flavorjones** [comment]
@Schwad Thanks for the thoughtful idea!

I'm not totally sure I understand the case you're describing. Are you saying that, because no gem was available on the specified date, it's resolving to the most recent? If so, yeah, that seems suboptimal and I agree it should do something different.

Maybe we can pair on this a bit once you come up for air?

**Comment by Schwad** [comment]
No problem! And thanks for writing this awesome plugin. :) 

> Are you saying that, because no gem was available on the specified date, it's resolving to the most recent? If so, yeah, that seems suboptimal and I agree it should do something different.

Yes sorry if I didn't articulate this well enough 😅 . That sounds like a great plan and I'll message you once sin city ruby wraps up!

**Comment by Schwad** [comment]
I'm going to close this issue in favor of newer ideas since our pairing session
